// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1j4-KWSdZZ8GZZte5oAqMX_RSiNqDsKE',
    appId: '1:352649450594:web:a6ad6ddb4e380487dfed3b',
    messagingSenderId: '352649450594',
    projectId: 'diet-app-batuhan',
    authDomain: 'diet-app-batuhan.firebaseapp.com',
    storageBucket: 'diet-app-batuhan.appspot.com',
    measurementId: 'G-DFPM4ZVDGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqcRqJVuxuWWLaRTFPttjsUaC6nH1Ag2k',
    appId: '1:352649450594:android:64ed459d7b67ab74dfed3b',
    messagingSenderId: '352649450594',
    projectId: 'diet-app-batuhan',
    storageBucket: 'diet-app-batuhan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY9LYLBwT0inBnj8xvjWBfMBs7EUZolgI',
    appId: '1:352649450594:ios:987e2dd33997bf6edfed3b',
    messagingSenderId: '352649450594',
    projectId: 'diet-app-batuhan',
    storageBucket: 'diet-app-batuhan.appspot.com',
    iosClientId: '352649450594-hp4g0bcr79gr8704rj3obas1a137nnka.apps.googleusercontent.com',
    iosBundleId: 'com.example.dietApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY9LYLBwT0inBnj8xvjWBfMBs7EUZolgI',
    appId: '1:352649450594:ios:48acf7f14d51259cdfed3b',
    messagingSenderId: '352649450594',
    projectId: 'diet-app-batuhan',
    storageBucket: 'diet-app-batuhan.appspot.com',
    iosClientId: '352649450594-m8ciqckceqi5cvq0h40kfde89oqb063a.apps.googleusercontent.com',
    iosBundleId: 'com.example.dietApp.RunnerTests',
  );
}
